/*
MIT License

Copyright (c) 2022 Allen Dang

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

//This file is automatically generated by generator.lua from https://github.com/gucio321/cimmarkdown
//based on imgui_markdown.h file version XXX from imgui_markdown https://github.com/juliettef/imgui_markdown

#include "imgui_markdown.h"
#include "cimmarkdown.h"

CIMGUI_API void mdDefaultMarkdownTooltipCallback(const MarkdownTooltipCallbackData* data_)
{
    return ImGui::defaultMarkdownTooltipCallback(data_);
}
CIMGUI_API void mdDefaultMarkdownLinkCallback(const MarkdownLinkCallbackData* data_)
{
    return ImGui::defaultMarkdownLinkCallback(data_);
}
CIMGUI_API void mdDefaultMarkdownFormatCallback(const MarkdownFormatInfo markdownFormatInfo_,bool start_)
{
    return ImGui::defaultMarkdownFormatCallback(markdownFormatInfo_,start_);
}
CIMGUI_API void mdMarkdown(const char* markdown,size_t markdownLength,const MarkdownConfig* mdConfig)
{
    if (mdConfig == NULL)
    {
        return ImGui::Markdown(markdown,markdownLength, {});
    }
    return ImGui::Markdown(markdown,markdownLength,*mdConfig);
}