//This file is automatically generated by generator.lua from https://github.com/gucio321/cimmarkdown
//based on imgui_markdown.h file version XXX from imgui_markdown https://github.com/juliettef/imgui_markdown

#include "imgui_markdown.h"
#include "cimmarkdown.h"

CIMGUI_API void mdDefaultMarkdownTooltipCallback(MarkdownTooltipCallbackData data_)
{
    return ImGui::defaultMarkdownTooltipCallback(data_);
}
CIMGUI_API void mdDefaultMarkdownFormatCallback(const MarkdownFormatInfo markdownFormatInfo_,bool start_)
{
    return ImGui::defaultMarkdownFormatCallback(markdownFormatInfo_,start_);
}
CIMGUI_API void mdMarkdown(const char* markdown,size_t markdownLength,const MarkdownConfig* mdConfig)
{
    if (mdConfig == NULL)
    {
        return ImGui::Markdown(markdown,markdownLength, {});
    }
    return ImGui::Markdown(markdown,markdownLength,*mdConfig);
}