/*
MIT License

Copyright (c) 2022 Allen Dang

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

//This file is automatically generated by generator.lua from https://github.com/gucio321/cimmarkdown
//based on imgui_markdown.h file version XXX from imgui_markdown https://github.com/juliettef/imgui_markdown
#ifndef CIMMARKDOWN_INCLUDED
#define CIMMARKDOWN_INCLUDED

#define NUMHEADINGS 3 // this is because struct field in imgui_markdown is static so we can't wrap it to C

#include "cimgui.h"

#ifdef CIMGUI_DEFINE_ENUMS_AND_STRUCTS

typedef struct MarkdownConfig MarkdownConfig;
typedef struct MarkdownLinkCallbackData MarkdownLinkCallbackData;
struct MarkdownLinkCallbackData
{
        const char* text;
        int textLength;
        const char* link;
        int linkLength;
        void* userData;
        bool isImage;
};
typedef struct MarkdownTooltipCallbackData MarkdownTooltipCallbackData;
struct MarkdownTooltipCallbackData
{
        MarkdownLinkCallbackData linkData;
        const char* linkIcon;
};
typedef struct MarkdownImageData MarkdownImageData;
struct MarkdownImageData
{
        bool isValid;
        bool useLinkCallback;
        ImTextureID user_texture_id;
        ImVec2 size;
        ImVec2 uv0;
        ImVec2 uv1;
        ImVec4 tint_col;
        ImVec4 border_col;
};
typedef enum {
         NORMAL_TEXT,
         HEADING,
         UNORDERED_LIST,
         LINK,
         EMPHASIS,
    }MarkdownFormatType;
typedef struct MarkdownFormatInfo MarkdownFormatInfo;
struct MarkdownFormatInfo
{
        MarkdownFormatType type;
        int32_t level;
        bool itemHovered;
        const MarkdownConfig* config;
};
typedef void MarkdownLinkCallback( MarkdownLinkCallbackData data );
typedef void MarkdownTooltipCallback( MarkdownTooltipCallbackData data );
typedef MarkdownImageData MarkdownImageCallback( MarkdownLinkCallbackData data );
typedef void MarkdownFormalCallback( const MarkdownFormatInfo markdownFormatInfo_, bool start_ );
typedef struct MarkdownHeadingFormat MarkdownHeadingFormat;
struct MarkdownHeadingFormat
{
        ImFont* font;
        bool separator;
};
struct MarkdownConfig
{
        MarkdownLinkCallback* linkCallback;
        MarkdownTooltipCallback* tooltipCallback;
        MarkdownImageCallback* imageCallback;
        const char* linkIcon;
        MarkdownHeadingFormat headingFormats[ NUMHEADINGS ];
        void* userData;
        MarkdownFormalCallback* formatCallback;
};
#else

#endif // CIMGUI_DEFINE_ENUMS_AND_STRUCTS

#ifndef CIMGUI_DEFINE_ENUMS_AND_STRUCTS
typedef ImGui::MarkdownConfig MarkdownConfig;
typedef ImGui::MarkdownFormatInfo MarkdownFormatInfo;
typedef ImGui::MarkdownHeadingFormat MarkdownHeadingFormat;
typedef ImGui::MarkdownImageData MarkdownImageData;
typedef ImGui::MarkdownLinkCallbackData MarkdownLinkCallbackData;
typedef ImGui::MarkdownTooltipCallbackData MarkdownTooltipCallbackData;
typedef ImGui::MarkdownFormatType MarkdownFormatType;
#endif //CIMGUI_DEFINE_ENUMS_AND_STRUCTS

CIMGUI_API void defaultMarkdownTooltipCallback(MarkdownTooltipCallbackData data_);
CIMGUI_API void defaultMarkdownFormatCallback(const MarkdownFormatInfo markdownFormatInfo_,bool start_);
CIMGUI_API void Markdown(const char* markdown_,size_t markdownLength_,const MarkdownConfig* mdConfig_);



#endif //CIMMARKDOWN_INCLUDED